### ISSUE TITLE
Minecraft crashes after loading

### ISSUE THREAD

**Issue by michelle1574** [Minecraft-Transit-Railway/Minecraft-Transit-Railway#780]
**Expected Behaviour**
It would load normally, without weird behaviour
**Actual Behaviour**
It was loading normally, and when the progressbar was full, Minecraft closed

**Reproduction Steps**
Steps to reproduce the behaviour:

1. Download the mod zip file: https://www.mediafire.com/file/nwd50ouyzs4juic/MODS-For-RailwayAdventure.zip/file
3. Open minecraft

**Crash Report**
https://mclo.gs/gGcqaME

**Environment**

- Minecraft Version: 1.19.4 Forge
- Installed Mods: (ZIP FILE contains all mods I have)

**Comment by kettle-7** [comment]
You'll need to allocate more memory to the game to fit all the mods you're using. To do this on the official launcher:
1) Open your launcher;
2) Go to the "installations" tab of the launcher at the top and edit the installation you're using with MTR;
3) There should be a dropdown or tab for either java settings or just advanced options
4) If there's a box to edit the allocated memory then set the minimum to 512M and the maximum to 6144M
5) Otherwise there should be a java arguments option, if it contains -Xms or -Xmx with another number after it then remove that
6) Then add -Xms512M -Xmx6000M to the end of the text box

**Comment by Kenny-Hui** [comment]
The textures of all your installed mods is too much for your GPU to handle.
Try tuning down the settings (For example turn off OptiFine connected texture), or reduce the amount of mods installed.
